collections:
  projects:
    output: true
    permalink: /projects/:path/
  competitions:
    output: true
    permalink: /competitions/:path/
  cooperations:
    output: false

prose:
  media: 'asset/image'
  ignore:
    - README.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /projects
    - /competitions
    - /blog
    - /asset

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      google_analytics_account: "UA-XXXX-Y"

permalink: "/blog/:categories/:year/:month/:day/:title/"
