collections:
  projects:
    output: true
    permalink: /projects/:path/
  competitions:
    output: false
  cooperations:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      google_analytics_account: "UA-XXXX-Y"
