collections:
  projects:
    output: true
    permalink: /projects/:path/
  competitions:
    output: true
    permalink: /competitions/:path/
  cooperations:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      google_analytics_account: "UA-XXXX-Y"

permalink: "/blog/:categories/:year/:month/:day/:title/"
